
  server:
    port: 8080
  spring:
    mail:
      host: smtp.qq.com
      port: 25
      username: 351234359@qq.com
      password: mixgnhwvyubibica
      default-encoding: UTF-8

    datasource:
      url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      database: mysql
      show-sql: true
      generate-ddl: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: update
    thymeleaf:
      check-template-location: true
      prefix: classpath:/templates/
      excluded-view-names:
      view-names:
      suffix: .html
      mode: HTML5
      encoding: UTF-8
      servlet:
        content-type: text/html